<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function challenge_submission_theme() {

  return [
    'challenge_submission_page_theme' => [
      'render element' => 'form',
      'template' => 'submission-form-theme-page',
    ],
    'challenge_submission_french_page_theme' => [
      'render element' => 'form',
      'template' => 'submission-form-french-theme-page',
    ],
  ];
}
